skip_repository_checks_reason: I want to skip all checks
skip_license_checks_reason: I want to skip all checks
skip_registry_checks_reason: I want to skip all checks
skip_citation_checks_reason: I want to skip all checks
skip_checklist_checks_reason: I want to skip all checks
