name: fair-software

on: push

jobs:
  verify:
    name: "fair-software"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out a copy of your repository
        # Maybe we do not need to check out the repo?

      - name: Repository Meta
        uses: varunsridharan/action-repository-meta@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Testing URL"
        run: echo REPOSITORY_GITHUB_URL=$REPOSITORY_GITHUB_URL

      - uses: fair-software/badge@url
        name: (1/5) Use a publicly accessible repository with version control
        with:
          SWITCH: "repository"
          REPOSITORY: ${{ env.REPOSITORY_HOMEPAGE_URL }}

      - uses: fair-software/badge@master
        name: (2/5) Add a license
        with:
          SWITCH: "license"

      - uses: fair-software/badge@master
        name: (3/5) Register your code in a community registry
        with:
          SWITCH: "registry"

      - uses: fair-software/badge@master
        name: (4/5) Enable citation of the software
        with:
          SWITCH: "citation"

      - uses: fair-software/badge@master
        name: (5/5) Use a software quality checklist
        with:
          SWITCH: "checklist"


