name: fair-software

on: push

jobs:
  verify:
    name: "fair-software"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out a copy of your repository

      - uses: fair-software/badge@master

      - name: (1/5) Use a publicly accessible repository with version control
        shell: bash -l {0}
        run: echo "repository"

      - name: (2/5) Add a license
        shell: bash -l {0}
        run: echo "license"

      - name: (3/5) Register your code in a community registry
        shell: bash -l {0}
        run: "/usr/local/bin/python3 /data/3-registry/check_registry.py"

      - name: (4/5) Enable citation of the software
        shell: bash -l {0}
        run: echo "citation"

      - name: (5/5) Use a software quality checklist
        shell: bash -l {0}
        run: echo "checklist"
