name: fair-software

on: push

jobs:
  verify:
    name: "fair-software"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out a copy of your repository
        # Maybe we do not need to check out the repo?

      - uses: fair-software/badge@packaging
        name: Measure compliance with fair-software.eu recommendations
        with:
          SWITCH: "repository"
          REPOSITORY: '${{ github.repository }}'
